// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_alert_configuration` describes an Alert Configuration.
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find **group_id** in the official documentation.
func LookupAlertConfiguration(ctx *pulumi.Context, args *GetAlertConfigurationArgs) (*GetAlertConfigurationResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["alertConfigurationId"] = args.AlertConfigurationId
		inputs["projectId"] = args.ProjectId
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getAlertConfiguration:getAlertConfiguration", inputs)
	if err != nil {
		return nil, err
	}
	return &GetAlertConfigurationResult{
		AlertConfigurationId: outputs["alertConfigurationId"],
		Created: outputs["created"],
		Enabled: outputs["enabled"],
		EventType: outputs["eventType"],
		Matchers: outputs["matchers"],
		MetricThreshold: outputs["metricThreshold"],
		Notifications: outputs["notifications"],
		ProjectId: outputs["projectId"],
		Updated: outputs["updated"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getAlertConfiguration.
type GetAlertConfigurationArgs struct {
	// Unique identifier for the alert configuration.
	AlertConfigurationId interface{}
	// The ID of the project where the alert configuration will create.
	ProjectId interface{}
}

// A collection of values returned by getAlertConfiguration.
type GetAlertConfigurationResult struct {
	AlertConfigurationId interface{}
	// Timestamp in ISO 8601 date and time format in UTC when this alert configuration was created.
	Created interface{}
	// If set to true, the alert configuration is enabled. If enabled is not exported it is set to false.
	Enabled interface{}
	// The type of event that will trigger an alert.
	// Alert type. Possible values:
	// - Host
	// - `OUTSIDE_METRIC_THRESHOLD`
	// - `HOST_RESTARTED`
	// - `HOST_UPGRADED`
	// - `HOST_NOW_SECONDARY`
	// - `HOST_NOW_PRIMARY`
	// - Replica set
	// - `NO_PRIMARY`
	// - `TOO_MANY_ELECTIONS`
	// Sharded cluster
	// - `CLUSTER_MONGOS_IS_MISSING`
	// - `User`
	// - `JOINED_GROUP`
	// - `REMOVED_FROM_GROUP`
	// - `USER_ROLES_CHANGED_AUDIT`
	// - Project
	// - `USERS_AWAITING_APPROVAL`
	// - `USERS_WITHOUT_MULTI_FACTOR_AUTH`
	// - `GROUP_CREATED`
	// - Team
	// - `JOINED_TEAM`
	// - `REMOVED_FROM_TEAM`
	// - Organization
	// - `INVITED_TO_ORG`
	// - `JOINED_ORG`
	// - Data Explorer
	// - `DATA_EXPLORER`
	// - `DATA_EXPLORER_CRUD`
	// - Billing
	// - `CREDIT_CARD_ABOUT_TO_EXPIRE`
	// - `CHARGE_SUCCEEDED`
	// - `INVOICE_CLOSED`
	EventType interface{}
	Matchers interface{}
	MetricThreshold interface{}
	Notifications interface{}
	ProjectId interface{}
	// Timestamp in ISO 8601 date and time format in UTC when this alert configuration was last updated.
	Updated interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
