// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_cloud_provider_snapshot_restore_job` provides a Cloud Provider Snapshot Restore Job entry datasource. Gets all cloud provider snapshot restore jobs for the specified cluster.
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find `groupId` in the official documentation.
func LookupCloudProviderSnapshotRestoreJob(ctx *pulumi.Context, args *GetCloudProviderSnapshotRestoreJobArgs) (*GetCloudProviderSnapshotRestoreJobResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["clusterName"] = args.ClusterName
		inputs["jobId"] = args.JobId
		inputs["projectId"] = args.ProjectId
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getCloudProviderSnapshotRestoreJob:getCloudProviderSnapshotRestoreJob", inputs)
	if err != nil {
		return nil, err
	}
	return &GetCloudProviderSnapshotRestoreJobResult{
		Cancelled: outputs["cancelled"],
		ClusterName: outputs["clusterName"],
		CreatedAt: outputs["createdAt"],
		DeliveryType: outputs["deliveryType"],
		DeliveryUrls: outputs["deliveryUrls"],
		Expired: outputs["expired"],
		ExpiresAt: outputs["expiresAt"],
		FinishedAt: outputs["finishedAt"],
		JobId: outputs["jobId"],
		ProjectId: outputs["projectId"],
		SnapshotId: outputs["snapshotId"],
		TargetClusterName: outputs["targetClusterName"],
		TargetProjectId: outputs["targetProjectId"],
		Timestamp: outputs["timestamp"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getCloudProviderSnapshotRestoreJob.
type GetCloudProviderSnapshotRestoreJobArgs struct {
	// The name of the Atlas cluster for which you want to retrieve the restore job.
	ClusterName interface{}
	// The unique identifier of the restore job to retrieve.
	JobId interface{}
	// The unique identifier of the project for the Atlas cluster.
	ProjectId interface{}
}

// A collection of values returned by getCloudProviderSnapshotRestoreJob.
type GetCloudProviderSnapshotRestoreJobResult struct {
	// Indicates whether the restore job was canceled.
	Cancelled interface{}
	ClusterName interface{}
	// UTC ISO 8601 formatted point in time when Atlas created the restore job.
	CreatedAt interface{}
	// Type of restore job to create. Possible values are: automated and download.
	DeliveryType interface{}
	// One or more URLs for the compressed snapshot files for manual download. Only visible if deliveryType is download.
	DeliveryUrls interface{}
	// Indicates whether the restore job expired.
	Expired interface{}
	// UTC ISO 8601 formatted point in time when the restore job expires.
	ExpiresAt interface{}
	// UTC ISO 8601 formatted point in time when the restore job completed.
	FinishedAt interface{}
	JobId interface{}
	ProjectId interface{}
	// Unique identifier of the source snapshot ID of the restore job.
	SnapshotId interface{}
	// Name of the target Atlas cluster to which the restore job restores the snapshot. Only visible if deliveryType is automated.
	TargetClusterName interface{}
	TargetProjectId interface{}
	// Timestamp in ISO 8601 date and time format in UTC when the snapshot associated to snapshotId was taken.
	Timestamp interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
