// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_cloud_provider_snapshot_restore_jobs` provides a Cloud Provider Snapshot Restore Jobs entry datasource. Gets all cloud provider snapshot restore jobs for the specified cluster.
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find `groupId` in the official documentation.
func LookupCloudProviderSnapshotRestoreJobs(ctx *pulumi.Context, args *GetCloudProviderSnapshotRestoreJobsArgs) (*GetCloudProviderSnapshotRestoreJobsResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["clusterName"] = args.ClusterName
		inputs["projectId"] = args.ProjectId
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getCloudProviderSnapshotRestoreJobs:getCloudProviderSnapshotRestoreJobs", inputs)
	if err != nil {
		return nil, err
	}
	return &GetCloudProviderSnapshotRestoreJobsResult{
		ClusterName: outputs["clusterName"],
		ProjectId: outputs["projectId"],
		Results: outputs["results"],
		TotalCount: outputs["totalCount"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getCloudProviderSnapshotRestoreJobs.
type GetCloudProviderSnapshotRestoreJobsArgs struct {
	// The name of the Atlas cluster for which you want to retrieve restore jobs.
	ClusterName interface{}
	// The unique identifier of the project for the Atlas cluster.
	ProjectId interface{}
}

// A collection of values returned by getCloudProviderSnapshotRestoreJobs.
type GetCloudProviderSnapshotRestoreJobsResult struct {
	ClusterName interface{}
	ProjectId interface{}
	// Includes cloudProviderSnapshotRestoreJob object for each item detailed in the results array section.
	Results interface{}
	TotalCount interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
