// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_custom_db_roles` describe all Custom DB Roles. This represents a custom db roles.
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find `groupId` in the official documentation.
func LookupCustomDbRoles(ctx *pulumi.Context, args *GetCustomDbRolesArgs) (*GetCustomDbRolesResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["projectId"] = args.ProjectId
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getCustomDbRoles:getCustomDbRoles", inputs)
	if err != nil {
		return nil, err
	}
	return &GetCustomDbRolesResult{
		ProjectId: outputs["projectId"],
		Results: outputs["results"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getCustomDbRoles.
type GetCustomDbRolesArgs struct {
	// The unique ID for the project to get all custom db roles.
	ProjectId interface{}
}

// A collection of values returned by getCustomDbRoles.
type GetCustomDbRolesResult struct {
	ProjectId interface{}
	// A list where each represents a custom db roles.
	Results interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
