// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_cluster` describes all Clusters by the provided project_id. The data source requires your Project ID.
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find group_id in the official documentation.
// 
// > **IMPORTANT:**
// <br> &#8226; Changes to cluster configurations can affect costs. Before making changes, please see [Billing](https://docs.atlas.mongodb.com/billing/).
// <br> &#8226; If your Atlas project contains a custom role that uses actions introduced in a specific MongoDB version, you cannot create a cluster with a MongoDB version less than that version unless you delete the custom role.
func LookupClusters(ctx *pulumi.Context, args *GetClustersArgs) (*GetClustersResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["projectId"] = args.ProjectId
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getClusters:getClusters", inputs)
	if err != nil {
		return nil, err
	}
	return &GetClustersResult{
		Plugin: outputs["plugin"],
		ProjectId: outputs["projectId"],
		Results: outputs["results"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getClusters.
type GetClustersArgs struct {
	// The unique ID for the project to get the clusters.
	ProjectId interface{}
}

// A collection of values returned by getClusters.
type GetClustersResult struct {
	Plugin interface{}
	ProjectId interface{}
	// A list where each represents a Cluster. See Cluster below for more details.
	Results interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
