// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_cloud_provider_snapshots` provides an Cloud Provider Snapshot entry datasource. Atlas Cloud Provider Snapshots provide localized backup storage using the native snapshot functionality of the cluster’s cloud service provider.
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find `groupId` in the official documentation.
func LookupCloudProviderSnapshots(ctx *pulumi.Context, args *GetCloudProviderSnapshotsArgs) (*GetCloudProviderSnapshotsResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["clusterName"] = args.ClusterName
		inputs["projectId"] = args.ProjectId
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getCloudProviderSnapshots:getCloudProviderSnapshots", inputs)
	if err != nil {
		return nil, err
	}
	return &GetCloudProviderSnapshotsResult{
		ClusterName: outputs["clusterName"],
		ProjectId: outputs["projectId"],
		Results: outputs["results"],
		TotalCount: outputs["totalCount"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getCloudProviderSnapshots.
type GetCloudProviderSnapshotsArgs struct {
	// The name of the Atlas cluster that contains the snapshot you want to retrieve.
	ClusterName interface{}
	ProjectId interface{}
}

// A collection of values returned by getCloudProviderSnapshots.
type GetCloudProviderSnapshotsResult struct {
	ClusterName interface{}
	ProjectId interface{}
	// Includes cloudProviderSnapshot object for each item detailed in the results array section.
	Results interface{}
	TotalCount interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
