// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_custom_db_role` describe a Custom DB Role. This represents a custom db role.
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find group_id in the official documentation.
func LookupCustomDbRole(ctx *pulumi.Context, args *GetCustomDbRoleArgs) (*GetCustomDbRoleResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["inheritedRoles"] = args.InheritedRoles
		inputs["projectId"] = args.ProjectId
		inputs["roleName"] = args.RoleName
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getCustomDbRole:getCustomDbRole", inputs)
	if err != nil {
		return nil, err
	}
	return &GetCustomDbRoleResult{
		Actions: outputs["actions"],
		InheritedRoles: outputs["inheritedRoles"],
		ProjectId: outputs["projectId"],
		RoleName: outputs["roleName"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getCustomDbRole.
type GetCustomDbRoleArgs struct {
	InheritedRoles interface{}
	// The unique ID for the project to create the database user.
	ProjectId interface{}
	// Name of the custom role. 
	RoleName interface{}
}

// A collection of values returned by getCustomDbRole.
type GetCustomDbRoleResult struct {
	Actions interface{}
	InheritedRoles interface{}
	ProjectId interface{}
	RoleName interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
