// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_maintenance_window` provides a Maintenance Window entry datasource. Gets information regarding the configured maintenance window for a MongoDB Atlas project.
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find `groupId` in the official documentation.
func LookupMaintenanceWindow(ctx *pulumi.Context, args *GetMaintenanceWindowArgs) (*GetMaintenanceWindowResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["projectId"] = args.ProjectId
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getMaintenanceWindow:getMaintenanceWindow", inputs)
	if err != nil {
		return nil, err
	}
	return &GetMaintenanceWindowResult{
		DayOfWeek: outputs["dayOfWeek"],
		HourOfDay: outputs["hourOfDay"],
		NumberOfDeferrals: outputs["numberOfDeferrals"],
		ProjectId: outputs["projectId"],
		StartAsap: outputs["startAsap"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getMaintenanceWindow.
type GetMaintenanceWindowArgs struct {
	// The unique identifier of the project for the Maintenance Window.
	ProjectId interface{}
}

// A collection of values returned by getMaintenanceWindow.
type GetMaintenanceWindowResult struct {
	// Day of the week when you would like the maintenance window to start as a 1-based integer: S=1, M=2, T=3, W=4, T=5, F=6, S=7.
	DayOfWeek interface{}
	// Hour of the day when you would like the maintenance window to start. This parameter uses the 24-hour clock, where midnight is 0, noon is 12  (Time zone is UTC).
	HourOfDay interface{}
	// Number of times the current maintenance event for this project has been deferred, you can set a maximum of 2 deferrals.
	NumberOfDeferrals interface{}
	ProjectId interface{}
	// Flag indicating whether project maintenance has been directed to start immediately. If you request that maintenance begin immediately, this field returns true from the time the request was made until the time the maintenance event completes.
	StartAsap interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
