// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_network_peerings` describes all Network Peering Connections.
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find **group_id** in the official documentation.
func LookupNetworkPeeringConnections(ctx *pulumi.Context, args *GetNetworkPeeringConnectionsArgs) (*GetNetworkPeeringConnectionsResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["projectId"] = args.ProjectId
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getNetworkPeeringConnections:getNetworkPeeringConnections", inputs)
	if err != nil {
		return nil, err
	}
	return &GetNetworkPeeringConnectionsResult{
		ProjectId: outputs["projectId"],
		Results: outputs["results"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getNetworkPeeringConnections.
type GetNetworkPeeringConnectionsArgs struct {
	// The unique ID for the project to create the database user.
	ProjectId interface{}
}

// A collection of values returned by getNetworkPeeringConnections.
type GetNetworkPeeringConnectionsResult struct {
	ProjectId interface{}
	// A list where each represents a Network Peering Connection.
	Results interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
