// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_private_endpoint` describe a Private Endpoint. This represents a Private Endpoint Connection to retrieve details regarding a private endpoint by id in an Atlas project
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find group_id in the official documentation.
func LookupPrivateEndpoint(ctx *pulumi.Context, args *GetPrivateEndpointArgs) (*GetPrivateEndpointResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["privateLinkId"] = args.PrivateLinkId
		inputs["projectId"] = args.ProjectId
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getPrivateEndpoint:getPrivateEndpoint", inputs)
	if err != nil {
		return nil, err
	}
	return &GetPrivateEndpointResult{
		EndpointServiceName: outputs["endpointServiceName"],
		ErrorMessage: outputs["errorMessage"],
		InterfaceEndpoints: outputs["interfaceEndpoints"],
		PrivateLinkId: outputs["privateLinkId"],
		ProjectId: outputs["projectId"],
		Status: outputs["status"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getPrivateEndpoint.
type GetPrivateEndpointArgs struct {
	// Unique identifier of the AWS PrivateLink connection.
	PrivateLinkId interface{}
	// Unique identifier for the project.
	ProjectId interface{}
}

// A collection of values returned by getPrivateEndpoint.
type GetPrivateEndpointResult struct {
	// Name of the PrivateLink endpoint service in AWS. Returns null while the endpoint service is being created.
	EndpointServiceName interface{}
	// Error message pertaining to the AWS PrivateLink connection. Returns null if there are no errors.
	ErrorMessage interface{}
	// Unique identifiers of the interface endpoints in your VPC that you added to the AWS PrivateLink connection.
	InterfaceEndpoints interface{}
	PrivateLinkId interface{}
	ProjectId interface{}
	// Status of the AWS PrivateLink connection.
	// Returns one of the following values:
	Status interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
