// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_private_endpoint_link` describe a Private Endpoint Link. This represents a Private Endpoint Link Connection that wants to retrieve details in an Atlas project.
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find group_id in the official documentation.
func LookupPrivateEndpointInterfaceLink(ctx *pulumi.Context, args *GetPrivateEndpointInterfaceLinkArgs) (*GetPrivateEndpointInterfaceLinkResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["interfaceEndpointId"] = args.InterfaceEndpointId
		inputs["privateLinkId"] = args.PrivateLinkId
		inputs["projectId"] = args.ProjectId
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getPrivateEndpointInterfaceLink:getPrivateEndpointInterfaceLink", inputs)
	if err != nil {
		return nil, err
	}
	return &GetPrivateEndpointInterfaceLinkResult{
		ConnectionStatus: outputs["connectionStatus"],
		DeleteRequested: outputs["deleteRequested"],
		ErrorMessage: outputs["errorMessage"],
		InterfaceEndpointId: outputs["interfaceEndpointId"],
		PrivateLinkId: outputs["privateLinkId"],
		ProjectId: outputs["projectId"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getPrivateEndpointInterfaceLink.
type GetPrivateEndpointInterfaceLinkArgs struct {
	InterfaceEndpointId interface{}
	// Unique identifier of the AWS PrivateLink connection.
	PrivateLinkId interface{}
	// Unique identifier for the project.
	ProjectId interface{}
}

// A collection of values returned by getPrivateEndpointInterfaceLink.
type GetPrivateEndpointInterfaceLinkResult struct {
	// Status of the interface endpoint.
	// Returns one of the following values:
	ConnectionStatus interface{}
	// Indicates if Atlas received a request to remove the interface endpoint from the private endpoint connection.
	DeleteRequested interface{}
	// Error message pertaining to the interface endpoint. Returns null if there are no errors.
	ErrorMessage interface{}
	InterfaceEndpointId interface{}
	PrivateLinkId interface{}
	ProjectId interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
