// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_x509_authentication_database_user` describe a X509 Authentication Database User. This represents a X509 Authentication Database User.
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find group_id in the official documentation.
func LookupX509AuthenticationDatabaseUser(ctx *pulumi.Context, args *GetX509AuthenticationDatabaseUserArgs) (*GetX509AuthenticationDatabaseUserResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["projectId"] = args.ProjectId
		inputs["username"] = args.Username
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getX509AuthenticationDatabaseUser:getX509AuthenticationDatabaseUser", inputs)
	if err != nil {
		return nil, err
	}
	return &GetX509AuthenticationDatabaseUserResult{
		Certificates: outputs["certificates"],
		CustomerX509Cas: outputs["customerX509Cas"],
		ProjectId: outputs["projectId"],
		Username: outputs["username"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getX509AuthenticationDatabaseUser.
type GetX509AuthenticationDatabaseUserArgs struct {
	// Identifier for the Atlas project associated with the X.509 configuration.
	ProjectId interface{}
	// Username of the database user to create a certificate for.
	Username interface{}
}

// A collection of values returned by getX509AuthenticationDatabaseUser.
type GetX509AuthenticationDatabaseUserResult struct {
	// Array of objects where each details one unexpired database user certificate.
	Certificates interface{}
	CustomerX509Cas interface{}
	ProjectId interface{}
	Username interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
