// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// `mongodbatlas_maintenance_window` provides a resource to schedule a maintenance window for your MongoDB Atlas Project and/or set to defer a scheduled maintenance up to two times.
// 
// > **NOTE:** Groups and projects are synonymous terms. You may find `groupId` in the official documentation.
// 
// ## Maintenance Window Considerations:
// 
// - Urgent Maintenance Activities Cannot Wait: Urgent maintenance activities such as security patches cannot wait for your chosen window. Atlas will start those maintenance activities when needed.
// 
// Once maintenance is scheduled for your cluster, you cannot change your maintenance window until the current maintenance efforts have completed.
// - Maintenance Requires Replica Set Elections: Atlas performs maintenance the same way as the manual maintenance procedure. This requires at least one replica set election during the maintenance window per replica set.
// - Maintenance Starts As Close to the Hour As Possible: Maintenance always begins as close to the scheduled hour as possible, but in-progress cluster updates or expected system issues could delay the start time.
type MaintenanceWindow struct {
	s *pulumi.ResourceState
}

// NewMaintenanceWindow registers a new resource with the given unique name, arguments, and options.
func NewMaintenanceWindow(ctx *pulumi.Context,
	name string, args *MaintenanceWindowArgs, opts ...pulumi.ResourceOpt) (*MaintenanceWindow, error) {
	if args == nil || args.ProjectId == nil {
		return nil, errors.New("missing required argument 'ProjectId'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["dayOfWeek"] = nil
		inputs["defer"] = nil
		inputs["hourOfDay"] = nil
		inputs["numberOfDeferrals"] = nil
		inputs["projectId"] = nil
	} else {
		inputs["dayOfWeek"] = args.DayOfWeek
		inputs["defer"] = args.Defer
		inputs["hourOfDay"] = args.HourOfDay
		inputs["numberOfDeferrals"] = args.NumberOfDeferrals
		inputs["projectId"] = args.ProjectId
	}
	inputs["startAsap"] = nil
	s, err := ctx.RegisterResource("mongodbatlas:index/maintenanceWindow:MaintenanceWindow", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &MaintenanceWindow{s: s}, nil
}

// GetMaintenanceWindow gets an existing MaintenanceWindow resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMaintenanceWindow(ctx *pulumi.Context,
	name string, id pulumi.ID, state *MaintenanceWindowState, opts ...pulumi.ResourceOpt) (*MaintenanceWindow, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["dayOfWeek"] = state.DayOfWeek
		inputs["defer"] = state.Defer
		inputs["hourOfDay"] = state.HourOfDay
		inputs["numberOfDeferrals"] = state.NumberOfDeferrals
		inputs["projectId"] = state.ProjectId
		inputs["startAsap"] = state.StartAsap
	}
	s, err := ctx.ReadResource("mongodbatlas:index/maintenanceWindow:MaintenanceWindow", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &MaintenanceWindow{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *MaintenanceWindow) URN() *pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *MaintenanceWindow) ID() *pulumi.IDOutput {
	return r.s.ID()
}

// Day of the week when you would like the maintenance window to start as a 1-based integer: S=1, M=2, T=3, W=4, T=5, F=6, S=7.
func (r *MaintenanceWindow) DayOfWeek() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["dayOfWeek"])
}

// Defer maintenance for the given project for one week.
func (r *MaintenanceWindow) Defer() *pulumi.BoolOutput {
	return (*pulumi.BoolOutput)(r.s.State["defer"])
}

// Hour of the day when you would like the maintenance window to start. This parameter uses the 24-hour clock, where midnight is 0, noon is 12 (Time zone is UTC).
func (r *MaintenanceWindow) HourOfDay() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["hourOfDay"])
}

// Number of times the current maintenance event for this project has been deferred, you can set a maximum of 2 deferrals.
func (r *MaintenanceWindow) NumberOfDeferrals() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["numberOfDeferrals"])
}

// The unique identifier of the project for the Maintenance Window.
func (r *MaintenanceWindow) ProjectId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["projectId"])
}

// Flag indicating whether project maintenance has been directed to start immediately. If you request that maintenance begin immediately, this field returns true from the time the request was made until the time the maintenance event completes.
func (r *MaintenanceWindow) StartAsap() *pulumi.BoolOutput {
	return (*pulumi.BoolOutput)(r.s.State["startAsap"])
}

// Input properties used for looking up and filtering MaintenanceWindow resources.
type MaintenanceWindowState struct {
	// Day of the week when you would like the maintenance window to start as a 1-based integer: S=1, M=2, T=3, W=4, T=5, F=6, S=7.
	DayOfWeek interface{}
	// Defer maintenance for the given project for one week.
	Defer interface{}
	// Hour of the day when you would like the maintenance window to start. This parameter uses the 24-hour clock, where midnight is 0, noon is 12 (Time zone is UTC).
	HourOfDay interface{}
	// Number of times the current maintenance event for this project has been deferred, you can set a maximum of 2 deferrals.
	NumberOfDeferrals interface{}
	// The unique identifier of the project for the Maintenance Window.
	ProjectId interface{}
	// Flag indicating whether project maintenance has been directed to start immediately. If you request that maintenance begin immediately, this field returns true from the time the request was made until the time the maintenance event completes.
	StartAsap interface{}
}

// The set of arguments for constructing a MaintenanceWindow resource.
type MaintenanceWindowArgs struct {
	// Day of the week when you would like the maintenance window to start as a 1-based integer: S=1, M=2, T=3, W=4, T=5, F=6, S=7.
	DayOfWeek interface{}
	// Defer maintenance for the given project for one week.
	Defer interface{}
	// Hour of the day when you would like the maintenance window to start. This parameter uses the 24-hour clock, where midnight is 0, noon is 12 (Time zone is UTC).
	HourOfDay interface{}
	// Number of times the current maintenance event for this project has been deferred, you can set a maximum of 2 deferrals.
	NumberOfDeferrals interface{}
	// The unique identifier of the project for the Maintenance Window.
	ProjectId interface{}
}
