// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"github.com/pulumi/pulumi/sdk/go/pulumi/config"
)

// MongoDB Atlas Programmatic Private Key
func GetPrivateKey(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "mongodbatlas:privateKey")
	if err == nil {
		return v
	}
	if dv, ok := getEnvOrDefault("", nil, "MONGODB_ATLAS_PRIVATE_KEY").(string); ok {
		return dv
	}
	return v
}

// MongoDB Atlas Programmatic Public Key
func GetPublicKey(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "mongodbatlas:publicKey")
	if err == nil {
		return v
	}
	if dv, ok := getEnvOrDefault("", nil, "MONGODB_ATLAS_PUBLIC_KEY").(string); ok {
		return dv
	}
	return v
}
