# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from . import utilities, tables

class GetCustomDbRolesResult:
    """
    A collection of values returned by getCustomDbRoles.
    """
    def __init__(__self__, project_id=None, results=None, id=None):
        if project_id and not isinstance(project_id, str):
            raise TypeError("Expected argument 'project_id' to be a str")
        __self__.project_id = project_id
        if results and not isinstance(results, list):
            raise TypeError("Expected argument 'results' to be a list")
        __self__.results = results
        """
        A list where each represents a custom db roles.
        """
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        __self__.id = id
        """
        id is the provider-assigned unique ID for this managed resource.
        """

async def get_custom_db_roles(project_id=None,opts=None):
    """
    `mongodbatlas_custom_db_roles` describe all Custom DB Roles. This represents a custom db roles.
    
    > **NOTE:** Groups and projects are synonymous terms. You may find `groupId` in the official documentation.
    """
    __args__ = dict()

    __args__['projectId'] = project_id
    __ret__ = await pulumi.runtime.invoke('mongodbatlas:index/getCustomDbRoles:getCustomDbRoles', __args__, opts=opts)

    return GetCustomDbRolesResult(
        project_id=__ret__.get('projectId'),
        results=__ret__.get('results'),
        id=__ret__.get('id'))
