# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from . import utilities, tables

class GetNetworkPeeringConnectionsResult:
    """
    A collection of values returned by getNetworkPeeringConnections.
    """
    def __init__(__self__, project_id=None, results=None, id=None):
        if project_id and not isinstance(project_id, str):
            raise TypeError("Expected argument 'project_id' to be a str")
        __self__.project_id = project_id
        if results and not isinstance(results, list):
            raise TypeError("Expected argument 'results' to be a list")
        __self__.results = results
        """
        A list where each represents a Network Peering Connection.
        """
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        __self__.id = id
        """
        id is the provider-assigned unique ID for this managed resource.
        """

async def get_network_peering_connections(project_id=None,opts=None):
    """
    `mongodbatlas_network_peerings` describes all Network Peering Connections.
    
    > **NOTE:** Groups and projects are synonymous terms. You may find **group_id** in the official documentation.
    """
    __args__ = dict()

    __args__['projectId'] = project_id
    __ret__ = await pulumi.runtime.invoke('mongodbatlas:index/getNetworkPeeringConnections:getNetworkPeeringConnections', __args__, opts=opts)

    return GetNetworkPeeringConnectionsResult(
        project_id=__ret__.get('projectId'),
        results=__ret__.get('results'),
        id=__ret__.get('id'))
