# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from . import utilities, tables

class GetTeamResult:
    """
    A collection of values returned by getTeam.
    """
    def __init__(__self__, name=None, org_id=None, team_id=None, usernames=None, id=None):
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        __self__.name = name
        """
        The name of the team you want to create.
        """
        if org_id and not isinstance(org_id, str):
            raise TypeError("Expected argument 'org_id' to be a str")
        __self__.org_id = org_id
        if team_id and not isinstance(team_id, str):
            raise TypeError("Expected argument 'team_id' to be a str")
        __self__.team_id = team_id
        if usernames and not isinstance(usernames, list):
            raise TypeError("Expected argument 'usernames' to be a list")
        __self__.usernames = usernames
        """
        The users who are part of the organization.
        """
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        __self__.id = id
        """
        id is the provider-assigned unique ID for this managed resource.
        """

async def get_team(org_id=None,team_id=None,opts=None):
    """
    `mongodbatlas_teams` describes a Team. The resource requires your Organization ID, Project ID and Team ID.
    
    > **NOTE:** Groups and projects are synonymous terms. You may find group_id in the official documentation.
    """
    __args__ = dict()

    __args__['orgId'] = org_id
    __args__['teamId'] = team_id
    __ret__ = await pulumi.runtime.invoke('mongodbatlas:index/getTeam:getTeam', __args__, opts=opts)

    return GetTeamResult(
        name=__ret__.get('name'),
        org_id=__ret__.get('orgId'),
        team_id=__ret__.get('teamId'),
        usernames=__ret__.get('usernames'),
        id=__ret__.get('id'))
