// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * `mongodbatlas_teams` describes a Team. The resource requires your Organization ID, Project ID and Team ID.
 * 
 * > **NOTE:** Groups and projects are synonymous terms. You may find group_id in the official documentation.
 */
export function getTeam(args: GetTeamArgs, opts?: pulumi.InvokeOptions): Promise<GetTeamResult> {
    return pulumi.runtime.invoke("mongodbatlas:index/getTeam:getTeam", {
        "orgId": args.orgId,
        "teamId": args.teamId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTeam.
 */
export interface GetTeamArgs {
    /**
     * The unique identifier for the organization you want to associate the team with.
     */
    readonly orgId: string;
    /**
     * The unique identifier for the team.
     */
    readonly teamId: string;
}

/**
 * A collection of values returned by getTeam.
 */
export interface GetTeamResult {
    /**
     * The name of the team you want to create.
     */
    readonly name: string;
    readonly orgId: string;
    readonly teamId: string;
    /**
     * The users who are part of the organization.
     */
    readonly usernames: string[];
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
